package hibernate;
// Generated Oct 15, 2008 10:13:30 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
@SuppressWarnings("serial")
public class Customer  implements java.io.Serializable {

	
	private String username;
    private String firstName;
    private String lastName;
    private String street;
    private String city;
    private String state;
    private Integer zip;
    private String password;
    private Long ccNo;
    private Integer expiration;
    private Set<Itinerary> itineraries = new HashSet<Itinerary>(0);

    public Customer() {
    }

	
    public Customer(String username) {
        this.username = username;
    }
    public Customer(String username, String firstName, String lastName, String street, String city, String state, Integer zip, String password, Long ccNo, Integer expiration, Set<Itinerary> itineraries) {
       this.username = username;
       this.firstName = firstName;
       this.lastName = lastName;
       this.street = street;
       this.city = city;
       this.state = state;
       this.zip = zip;
       this.password = password;
       this.ccNo = ccNo;
       this.expiration = expiration;
       this.itineraries = itineraries;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Integer getZip() {
        return this.zip;
    }
    
    public void setZip(Integer zip) {
        this.zip = zip;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Long getCcNo() {
        return this.ccNo;
    }
    
    public void setCcNo(Long ccNo) {
        this.ccNo = ccNo;
    }
    public Integer getExpiration() {
        return this.expiration;
    }
    
    public void setExpiration(Integer expiration) {
        this.expiration = expiration;
    }
    public Set<Itinerary> getItineraries() {
        return this.itineraries;
    }
    
    public void setItineraries(Set<Itinerary> itineraries) {
        this.itineraries = itineraries;
    }




}


