package database.hibernate;
// Generated Oct 15, 2008 10:13:30 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Airline generated by hbm2java
 */
public class Airline  implements java.io.Serializable {


     private String code;
     private String name;
     private Set<Flight> flights = new HashSet<Flight>(0);

    public Airline() {
    }

	
    public Airline(String code) {
        this.code = code;
    }
    public Airline(String code, String name, Set<Flight> flights) {
       this.code = code;
       this.name = name;
       this.flights = flights;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Flight> getFlights() {
        return this.flights;
    }
    
    public void setFlights(Set<Flight> flights) {
        this.flights = flights;
    }




}


