package database.hibernate;
// Generated Oct 15, 2008 10:13:30 PM by Hibernate Tools 3.2.2.GA



/**
 * ItineraryId generated by hbm2java
 */
public class ItineraryId  implements java.io.Serializable {


     private int flightNo;
     private String username;

    public ItineraryId() {
    }

    public ItineraryId(int flightNo, String username) {
       this.flightNo = flightNo;
       this.username = username;
    }
   
    public int getFlightNo() {
        return this.flightNo;
    }
    
    public void setFlightNo(int flightNo) {
        this.flightNo = flightNo;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItineraryId) ) return false;
		 ItineraryId castOther = ( ItineraryId ) other; 
         
		 return (this.getFlightNo()==castOther.getFlightNo())
 && ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFlightNo();
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         return result;
   }   


}


