package database.hibernate;
// Generated Oct 15, 2008 10:13:30 PM by Hibernate Tools 3.2.2.GA



/**
 * Itinerary generated by hbm2java
 */
public class Itinerary  implements java.io.Serializable {


     private ItineraryId id;
     private Customer customer;
     private Flight flight;
     private String status;

    public Itinerary() {
    }

	
    public Itinerary(ItineraryId id, Customer customer, Flight flight) {
        this.id = id;
        this.customer = customer;
        this.flight = flight;
    }
    public Itinerary(ItineraryId id, Customer customer, Flight flight, String status) {
       this.id = id;
       this.customer = customer;
       this.flight = flight;
       this.status = status;
    }
   
    public ItineraryId getId() {
        return this.id;
    }
    
    public void setId(ItineraryId id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Flight getFlight() {
        return this.flight;
    }
    
    public void setFlight(Flight flight) {
        this.flight = flight;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


