package database.hibernate;

// Generated Sep 24, 2008 8:48:09 PM by Hibernate Tools 3.2.2.GA

/**
 * Airline generated by hbm2java
 */
public class Airline implements java.io.Serializable {

	private String code;
	private String name;

	public Airline() {
	}

	public Airline(String code) {
		this.code = code;
	}

	public Airline(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
