package database.hibernate;

// Generated Sep 24, 2008 8:48:09 PM by Hibernate Tools 3.2.2.GA

/**
 * Airport generated by hbm2java
 */
public class Airport implements java.io.Serializable {

	private String code;
	private String name;
	private String city;
	private String county;
	private String state;
	private String latitude1;
	private String latitude2;
	private String longitude1;
	private String longitude2;
	private String elevation;
	private String telephone;

	public Airport() {
	}

	public Airport(String code) {
		this.code = code;
	}

	public Airport(String code, String name, String city, String county,
			String state, String latitude1, String latitude2,
			String longitude1, String longitude2, String elevation,
			String telephone) {
		this.code = code;
		this.name = name;
		this.city = city;
		this.county = county;
		this.state = state;
		this.latitude1 = latitude1;
		this.latitude2 = latitude2;
		this.longitude1 = longitude1;
		this.longitude2 = longitude2;
		this.elevation = elevation;
		this.telephone = telephone;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getLatitude1() {
		return this.latitude1;
	}

	public void setLatitude1(String latitude1) {
		this.latitude1 = latitude1;
	}

	public String getLatitude2() {
		return this.latitude2;
	}

	public void setLatitude2(String latitude2) {
		this.latitude2 = latitude2;
	}

	public String getLongitude1() {
		return this.longitude1;
	}

	public void setLongitude1(String longitude1) {
		this.longitude1 = longitude1;
	}

	public String getLongitude2() {
		return this.longitude2;
	}

	public void setLongitude2(String longitude2) {
		this.longitude2 = longitude2;
	}

	public String getElevation() {
		return this.elevation;
	}

	public void setElevation(String elevation) {
		this.elevation = elevation;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
