package hibernate;

import java.util.EnumSet;
import java.util.HashMap;

// Generated Oct 15, 2008 10:13:30 PM by Hibernate Tools 3.2.2.GA

/**
 * Itinerary generated by hbm2java
 */
@SuppressWarnings("serial")
public class Itinerary implements java.io.Serializable {

   public enum EStatus {
      CANCELED("cancled"), BOOKED("booked"), RESERVED("reserved");

      private static final HashMap<String, EStatus> reverseMap = new HashMap<String, EStatus>();

      static {
         for (EStatus s : EnumSet.allOf(EStatus.class))
            reverseMap.put(s.toString(), s);
      }

      private String description;

      private EStatus(String description) {
         this.description = description;
      }

      @Override
      public String toString() {
         return this.description;
      }

      public static EStatus get(String code) {
         return reverseMap.get(code);
      }
   }

   private ItineraryId id;
   private Customer customer;
   private Flight flight;
   private EStatus status;

   public Itinerary() {
   }

   public Itinerary(ItineraryId id, Customer customer, Flight flight) {
      this.id = id;
      this.customer = customer;
      this.flight = flight;
   }

   public Itinerary(ItineraryId id, Customer customer, Flight flight, String status) {
      this.id = id;
      this.customer = customer;
      this.flight = flight;
      this.status = EStatus.get(status);
   }

   public ItineraryId getId() {
      return this.id;
   }

   public void setId(ItineraryId id) {
      this.id = id;
   }

   public Customer getCustomer() {
      return this.customer;
   }

   public void setCustomer(Customer customer) {
      this.customer = customer;
   }

   public Flight getFlight() {
      return this.flight;
   }

   public void setFlight(Flight flight) {
      this.flight = flight;
   }

   public String getStatus() {
      return this.status.toString();
   }

   public void setStatus(String status) {
      this.status = EStatus.get(status);
   }

}
